//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSIConfig.TencentQQ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="TencentQQ.qqOnlineWebServiceSoap")]
    public interface qqOnlineWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/qqCheckOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string qqCheckOnline(string qqCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/qqCheckOnline", ReplyAction="*")]
        System.Threading.Tasks.Task<string> qqCheckOnlineAsync(string qqCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface qqOnlineWebServiceSoapChannel : MSIConfig.TencentQQ.qqOnlineWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class qqOnlineWebServiceSoapClient : System.ServiceModel.ClientBase<MSIConfig.TencentQQ.qqOnlineWebServiceSoap>, MSIConfig.TencentQQ.qqOnlineWebServiceSoap {
        
        public qqOnlineWebServiceSoapClient() {
        }
        
        public qqOnlineWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public qqOnlineWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public qqOnlineWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public qqOnlineWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string qqCheckOnline(string qqCode) {
            return base.Channel.qqCheckOnline(qqCode);
        }
        
        public System.Threading.Tasks.Task<string> qqCheckOnlineAsync(string qqCode) {
            return base.Channel.qqCheckOnlineAsync(qqCode);
        }
    }
}
